### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by thewtex**
The site is migrated from manual HTML / JavaScript / CSS pages to a modern
website that:

- Reuses cite layout and styling without duplication.
- Uses the Material UI design framework.
- SEO support
- Offline support
- Builds on Gatsby for rapid development

The content is preserved with a few updates:

- NumFOCUS now holds the copyright
- CMake and IGSTK copyright were transferred to Kitware
- A different logo that had previously been created
- The ISC is now a Council instead of a Board of Directors

Changes are now made off `master`, and a GitHub Action will push to the `insightsoftwareconsortium-org` branch on merge to `master`. After merging this, I will enable up Netlify to create deploy previews for pull requests like this:

https://5e7430f2ed384e0008bda5a6--isc-thewtex.netlify.com/

### CODE REVIEW

**Comment by jcfr** [comment]
Looks great 🎉 

> Stephen Aylward with Luis Ibáñez at UNC (they are both now at Kitware)

-> `Stephen Aylward with Luis Ibáñez at UNC (Stephen is now at Kitware, Luis at Google)`

**Comment by jcfr** [comment]
What do you think of updating the "History of the ISC" to mention the transition to NumFOCUS ?

**Comment by blowekamp** [comment]
Looks great, thanks for updating it.

**Comment by thewtex** [comment]
Thanks for the reviews!

Yes, there are more content updates that should be made. It will be much easier to update and add content going forward. I will create issues for the items mentioned. If anyone notice more updates that could be made, please create an issue or PR :-).

**Pull request merged**
